apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  labels:
    build: cpic-navigation
  name: cpic-navigation
  namespace: eeanalytics-prod
spec:
  lookupPolicy:
    local: false
  tags:
    - annotations: null
      from:
        kind: DockerImage
        name: 'cpic-navigation:latest'
      importPolicy: {}
      name: latest
      referencePolicy:
        type: Source
status:
  dockerImageRepository: docker-registry.default.svc:5000/eeanalytics-prod/cpic-navigation
